on:
  push:
    tags:
      - "v*"
jobs:
  create-release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
    - uses: marvinpinto/action-automatic-releases@v1.1.2
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        draft: true